### ISSUE TITLE
Update Continuous Integration action

### ISSUE THREAD

**Issue by SampaioLeal** [Eureka-Shoulders/componentz#8]
Change to this to only run the action on push to develop and pull request to main branches
```yml
on:
  push:
    branches: 
      - develop
  pull_request:
    branches:
      - main
```
